import React from "react";
import RoadmapCard from "../components/RoadmapCard";

let cards = [
  {
    title: "Dex",
    text: "Swap your favourite tokens & benefit from the gasless swap",
  },
  {
    title: "Presale launchpad",
    text: "Stay ahead of the innovation from the crypto space",
  },
  {
    title: "DAO",
    text: "Help the ecosystem to grow by contributing to the protocol",
  },
  {
    title: "Futures",
    text: "Buy or sell derivative contracts on of trending tokens",
  },
  { title: "Options", text: "the options market" },
  {
    title: "LBP Launchpad",
    text: "A fair & secure way to invest in emerging coins",
  },
  {
    title: "Lending and Borrowing",
    text: "Maximize the potential of your capital gains",
  },
  {
    title: "Yield Aggregator",
    text: "Get your hands on extra APY generated by other protocols",
  },
  { title: "NFTs", text: "Own the first yield-bearing NFTs on the market" },
  {
    title: "Portfolio",
    text: "Display your wallet portfolio in a nice visual way",
  },
];
const Roadmap = () => {
  return (
    <div className="my-20 ">
      <div className="flex overflow-x-scroll scroll-smooth  gap-2 sm:gap-12 rounded-[60px] sm:p-12 lg:py-24 lg:px-52 bg-black  place-items-center border-none sm:border-dashed border-b border-l border-t border-gray-400">
        <RoadmapCard data={{ ...cards[0], img: "/assets/images/1.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[1], img: "/assets/images/2.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[2], img: "/assets/images/3.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[3], img: "/assets/images/4.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[4], img: "/assets/images/5.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[5], img: "/assets/images/6.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[6], img: "/assets/images/7.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[7], img: "/assets/images/8.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[8], img: "/assets/images/9.png" }} />
        <img
          src="/assets/images/line.png"
          className="self-end hidden sm:flex"
        />
        <RoadmapCard data={{ ...cards[9], img: "/assets/images/10.png" }} />
      </div>
      {/* <div className="flex gap-2 sm:gap-12 rounded-[60px] sm:p-12 lg:py-24 lg:px-52 bg-black place-items-center border-none sm:border-dashed border-b border-r  border-gray-400">
        <RoadmapCard data={{...cards[2], img:"/assets/images/3.png"}} />
        <img src="/assets/images/line.png" className="self-end hidden sm:flex"/>
        <RoadmapCard data={{...cards[3], img:"/assets/images/4.png"}} />
      </div>
      <div className="flex gap-2 sm:gap-12 rounded-[60px] sm:p-12 lg:py-24 lg:px-52 bg-black place-items-center border-none sm:border-dashed border-b border-l  border-gray-400">
        <RoadmapCard data={{...cards[4], img:"/assets/images/5.png"}} />
        <img src="/assets/images/line.png" className="self-end hidden sm:flex"/>
        <RoadmapCard data={{...cards[5], img:"/assets/images/6.png"}} />
      </div>
      <div className="flex gap-2 sm:gap-12 rounded-[60px] sm:p-12 lg:py-24 lg:px-52 bg-black place-items-center border-none sm:border-dashed border-b border-r  border-gray-400">
        <RoadmapCard data={{...cards[6], img:"/assets/images/7.png"}} />
        <img src="/assets/images/line.png" className="self-end hidden sm:flex"/>
        <RoadmapCard data={{...cards[7], img:"/assets/images/8.png"}} />
      </div>
      <div className="flex gap-2 sm:gap-12 rounded-[60px] sm:p-12 lg:py-24 lg:px-52 bg-black place-items-center border-none sm:border-dashed border-b border-l  border-gray-400">
        <RoadmapCard data={{...cards[8], img:"/assets/images/9.png"}} />
        <img src="/assets/images/line.png" className="self-end hidden sm:flex"/>
        <RoadmapCard data={{...cards[9], img:"/assets/images/10.png"}} />
      </div> */}
    </div>
  );
};

export default Roadmap;
